namespace StudentWebPortal.Model.Entity.Enum
{
    public enum Surahs
    {
        AlFatiha = 1,          // 1 - Al-Fatiha (The Opening)
        AlBaqarah = 2,         // 2 - Al-Baqarah (The Cow)
        AlImran = 3,           // 3 - Al-Imran (The Family of Imran)
        AnNisa = 4,            // 4 - An-Nisa (The Women)
        AlMaidah = 5,          // 5 - Al-Maidah (The Table Spread)
        AlAnam = 6,            // 6 - Al-An'am (The Cattle)
        AlAraf = 7,            // 7 - Al-A'raf (The Heights)
        AlAnfal = 8,           // 8 - Al-Anfal (The Spoils of War)
        AtTaubah = 9,          // 9 - At-Taubah (The Repentance)
        Yunus = 10,            // 10 - Yunus (Prophet Jonah)
        Hud = 11,              // 11 - Hud (Prophet Hud)
        Yusuf = 12,            // 12 - Yusuf (Prophet Joseph)
        ArRad = 13,            // 13 - Ar-Rad (The Thunder)
        Ibrahim = 14,          // 14 - Ibrahim (Prophet Abraham)
        AlHijr = 15,           // 15 - Al-Hijr (The Rocky Tract)
        AnNahl = 16,           // 16 - An-Nahl (The Bee)
        AlIsra = 17,           // 17 - Al-Isra (The Night Journey)
        AlKahf = 18,           // 18 - Al-Kahf (The Cave)
        Maryam = 19,           // 19 - Maryam (Mary)
        TaHa = 20,             // 20 - Ta-Ha (Ta-Ha)
        AlAnbiya = 21,         // 21 - Al-Anbiya (The Prophets)
        AlHajj = 22,           // 22 - Al-Hajj (The Pilgrimage)
        AlMuminun = 23,        // 23 - Al-Mu'minun (The Believers)
        AnNoor = 24,           // 24 - An-Noor (The Light)
        AlFurqan = 25,         // 25 - Al-Furqan (The Criterion)
        AshShuara = 26,        // 26 - Ash-Shuara (The Poets)
        AnNaml = 27,           // 27 - An-Naml (The Ants)
        AlQasas = 28,          // 28 - Al-Qasas (The Stories)
        AlAnkaboot = 29,       // 29 - Al-Ankaboot (The Spider)
        ArRoom = 30,           // 30 - Ar-Room (The Romans)
        Luqman = 31,           // 31 - Luqman (Luqman)
        AsSajda = 32,          // 32 - As-Sajda (The Prostration)
        AlAhzab = 33,          // 33 - Al-Ahzab (The Coalition)
        Saba = 34,             // 34 - Saba (Sheba)
        Fatir = 35,            // 35 - Fatir (Originator)
        YaSeen = 36,           // 36 - Ya-Seen (Ya-Seen)
        AsSaaffat = 37,        // 37 - As-Saaffat (Those Who Set the Ranks)
        Sad = 38,              // 38 - Sad (The Arabic Letter Sad)
        AzZumar = 39,          // 39 - Az-Zumar (The Companies)
        Gafir = 40,            // 40 - Gafir (The Forgiver)
        Fussilat = 41,         // 41 - Fussilat (Explained in Detail)
        AshShura = 42,         // 42 - Ash-Shura (Council)
        AzZukhruf = 43,        // 43 - Az-Zukhruf (The Ornaments of Gold)
        AdDukhan = 44,         // 44 - Ad-Dukhan (The Smoke)
        AlJasiyah = 45,        // 45 - Al-Jasiyah (The Kneeling)
        AlAhqaf = 46,          // 46 - Al-Ahqaf (The Sandhills)
        Muhammad = 47,         // 47 - Muhammad (Muhammad)
        AlFath = 48,           // 48 - Al-Fath (The Victory)
        AlHujuraat = 49,       // 49 - Al-Hujuraat (The Apartments)
        Qaf = 50,              // 50 - Qaf (The Letter Qaf)
        AdhDhariyat = 51,      // 51 - Adh-Dhariyat (The Scatterers)
        AtTur = 52,            // 52 - At-Tur (The Mountain)
        AnNajm = 53,           // 53 - An-Najm (The Star)
        AlQamar = 54,          // 54 - Al-Qamar (The Moon)
        ArRahman = 55,         // 55 - Ar-Rahman (The Most Gracious)
        AlWaqiah = 56,         // 56 - Al-Waqiah (The Event)
        AlHadid = 57,          // 57 - Al-Hadid (The Iron)
        AlMujadilah = 58,      // 58 - Al-Mujadilah (The Pleading Woman)
        AlHashr = 59,          // 59 - Al-Hashr (The Banishment)
        AlMumtahanah = 60,     // 60 - Al-Mumtahanah (The Woman Who Is Examined)
        AsSaff = 61,           // 61 - As-Saff (The Ranks)
        AlJumua = 62,          // 62 - Al-Jumua (The Congregation - Friday)
        AlMunafiqoon = 63,     // 63 - Al-Munafiqoon
        AtTaghabun = 64,       // 64 - At-Taghabun
        AtTalaq = 65,          // 65 - At-Talaq
        AtTahrim = 66,         // 66 - At-Tahrim
        AlMulk = 67,           // 67 - Al-Mulk
        AlQalam = 68,          // 68 - Al-Qalam
        AlHaqqah = 69,         // 69 - Al-Haqqah
        AlMaarij = 70,         // 70 - Al-Ma'arij
        Nuh = 71,              // 71 - Nuh
        AlJinn = 72,           // 72 - Al-Jinn
        AlMuzzammil = 73,      // 73 - Al-Muzzammil
        AlMuddaththir = 74,    // 74 - Al-Muddaththir
        AlQiyamah = 75,        // 75 - Al-Qiyamah
        AlInsan = 76,          // 76 - Al-Insan
        AlMursalaat = 77,      // 77 - Al-Mursalaat
        AnNaba = 78,           // 78 - An-Naba
        AnNaziat = 79,         // 79 - An-Naziat
        Abasa = 80,            // 80 - Abasa
        AtTakwir = 81,         // 81 - At-Takwir
        AlInfitaar = 82,       // 82 - Al-Infitaar
        AlMutaffifin = 83,     // 83 - Al-Mutaffifin
        AlInshiqaq = 84,       // 84 - Al-Inshiqaq
        AlBurooj = 85,         // 85 - Al-Burooj
        AtTariq = 86,          // 86 - At-Tariq
        AlAla = 87,            // 87 - Al-Ala
        AlGhaashiyah = 88,     // 88 - Al-Ghaashiyah
        AlFajr = 89,           // 89 - Al-Fajr
        AlBalad = 90,          // 90 - Al-Balad
        AshShams = 91,         // 91 - Ash-Shams
        AlLail = 92,           // 92 - Al-Lail
        AdDuha = 93,           // 93 - Ad-Duha
        AlInshirah = 94,       // 94 - Al-Inshirah
        AtTin = 95,            // 95 - At-Tin
        AlAlaq = 96,           // 96 - Al-Alaq
        AlQadr = 97,           // 97 - Al-Qadr
        AlBayyinah = 98,       // 98 - Al-Bayyinah
        AzZalzalah = 99,       // 99 - Az-Zalzalah
        AlAdiyat = 100,        // 100 - Al-Adiyat
        AlQariah = 101,        // 101 - Al-Qari'ah
        AtTakathur = 102,      // 102 - At-Takathur
        AlAsr = 103,           // 103 - Al-Asr
        AlHumazah = 104,       // 104 - Al-Humazah
        AlFil = 105,           // 105 - Al-Fil
        Quraish = 106,         // 106 - Quraish
        AlMaun = 107,          // 107 - Al-Maun
        AlKauthar = 108,       // 108 - Al-Kauthar
        AlKafirun = 109,       // 109 - Al-Kafirun
        AnNasr = 110,          // 110 - An-Nasr
        AlMasad = 111,         // 111 - Al-Masad
        AlIkhlas = 112,        // 112 - Al-Ikhlas
        AlFalaq = 113,         // 113 - Al-Falaq
        AnNas = 114            // 114 - An-Nas
    }
}
